In [1]:
import ipywidgets as widgets
import pandas as pd

style = {'description_width': 'initial'}

limit_case = widgets.IntSlider(
    value=1000,
    min=100,
    max=5000,
    step=1,
    description='Max Number of Case:',
    disabled=False,
    style=style)

In [2]:
def update_df_length(limit):
    
    df = pd.read_csv('melb_data.csv')
    df = df.iloc[0:limit, :]
    print("Number of rows in the dataset that have been successfully loaded:"+str(len(df)))

In [3]:
widgets.interactive(update_df_length, limit=limit_case)

interactive(children=(IntSlider(value=1000, description='Max Number of Case:', max=5000, min=100, style=Sliderâ€¦

In [4]:
df = pd.read_csv('melb_data.csv')
df[df['CouncilArea']!='Yarra']

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
38,Airport West,154 Halsey Rd,3,t,840000.0,PI,Nelson,3/09/2016,13.5,3042.0,...,2.0,1.0,303.0,225.0,2016.0,Moonee Valley,-37.71800,144.87800,Western Metropolitan,3464.0
39,Airport West,50 Bedford St,3,h,730000.0,VB,Nelson,3/12/2016,13.5,3042.0,...,2.0,1.0,0.0,145.0,1965.0,Moonee Valley,-37.72030,144.87550,Western Metropolitan,3464.0
40,Airport West,50 Bedford St,3,h,770000.0,SP,Nelson,4/03/2017,13.5,3042.0,...,2.0,1.0,0.0,145.0,1965.0,Moonee Valley,-37.72030,144.87550,Western Metropolitan,3464.0
41,Airport West,23 Hart St,2,h,603000.0,S,Nelson,4/03/2017,13.5,3042.0,...,1.0,1.0,272.0,84.0,1950.0,Moonee Valley,-37.72940,144.88800,Western Metropolitan,3464.0
42,Airport West,1/80 Hawker St,3,t,700000.0,S,Brad,4/03/2017,13.5,3042.0,...,2.0,2.0,239.0,134.0,2009.0,Moonee Valley,-37.72180,144.88370,Western Metropolitan,3464.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [5]:
df = pd.read_csv('melb_data.csv')
df[df['CouncilArea']!='Yarra']

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
38,Airport West,154 Halsey Rd,3,t,840000.0,PI,Nelson,3/09/2016,13.5,3042.0,...,2.0,1.0,303.0,225.0,2016.0,Moonee Valley,-37.71800,144.87800,Western Metropolitan,3464.0
39,Airport West,50 Bedford St,3,h,730000.0,VB,Nelson,3/12/2016,13.5,3042.0,...,2.0,1.0,0.0,145.0,1965.0,Moonee Valley,-37.72030,144.87550,Western Metropolitan,3464.0
40,Airport West,50 Bedford St,3,h,770000.0,SP,Nelson,4/03/2017,13.5,3042.0,...,2.0,1.0,0.0,145.0,1965.0,Moonee Valley,-37.72030,144.87550,Western Metropolitan,3464.0
41,Airport West,23 Hart St,2,h,603000.0,S,Nelson,4/03/2017,13.5,3042.0,...,1.0,1.0,272.0,84.0,1950.0,Moonee Valley,-37.72940,144.88800,Western Metropolitan,3464.0
42,Airport West,1/80 Hawker St,3,t,700000.0,S,Brad,4/03/2017,13.5,3042.0,...,2.0,2.0,239.0,134.0,2009.0,Moonee Valley,-37.72180,144.88370,Western Metropolitan,3464.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [6]:
unique_Regionname = df.Regionname.unique()

In [7]:
from ipywidgets import Layout

regions = widgets.SelectMultiple(
    options = unique_Regionname.tolist(),
    value = ['Western Metropolitan', 'South-Eastern Metropolitan'],
    description='Region',
    disabled=False,
    layout = Layout(width='50%', height='80px', display='flex')
)

In [8]:
regions

SelectMultiple(description='Region', index=(1, 4), layout=Layout(display='flex', height='80px', width='50%'), â€¦

In [9]:
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20,10))
widgets.interactive(update_map, district = district, category = category, limit=limit_case)

NameError: name 'plt' is not defined