In [7]:
import random
import pandas as pd
import numpy as np
import string
import names
from faker import Faker

In [8]:
fake = Faker(['en_UK','fr_FR'])

In [9]:
#columns of user_info
users_columns = ['user_id','age','country_code','was_referred',
          'onboarding_completed_at','t2_upgrade_at','t3_upgrade_at',
         'became_premium_at',
         'premium_tier', 'is_fraud']

#columns of transaction_info
transaction_columns = ['user_id','transaction_id','timestamp','event_kind','currency','amount_in_eur']

In [10]:
event_kinds=['fiat_deposit','fiat_withdrawal','crypto_deposit','crypto_withdrawal','exchange']
currencies = ['BTC_USD','BTC_EUR','ETH_EUR','ETH_USD','USD_ETH','EUR_ETH','EUR_BTC','USD_BTC']

In [11]:
#user_info creation

df_users = pd.DataFrame()
for index in range(1500):
    df_users.at[index,'user_id'] = int(index)
    df_users.at[index,'country_code'] = fake.country_code()
    df_users.at[index,'age'] = np.random.randint(18,100)
    df_users.at[index,'was_referred'] = np.random.randint(0,2)
    df_users.at[index,'onboarding_completed_at'] = fake.date_between(start_date="-4y",end_date='today')
    df_users.at[index,'t2_upgrade_at'] = fake.date_between(start_date=df_users.at[index,'onboarding_completed_at'],end_date='today')
    df_users.at[index,'t3_upgrade_at'] = fake.date_between(start_date=df_users.at[index,'t2_upgrade_at'],end_date='today')
    df_users.at[index,'became_premium_at'] = fake.date_between(start_date=df_users.at[index,'t3_upgrade_at'],end_date='today')
    df_users.at[index,'premium_tier'] = np.random.randint(0,3)
    df_users.at[index,'is_fraud'] = np.random.choice(np.arange(0, 2), p=[0.995, 0.005])
df_users.head(5)

,user_id,country_code,age,was_referred,onboarding_completed_at,t2_upgrade_at,t3_upgrade_at,became_premium_at,premium_tier,is_fraud
0,0.0,SM,81.0,0.0,2021-05-26,2021-09-12,2021-09-28,2021-10-07,0.0,0.0
1,1.0,TH,93.0,1.0,2019-12-31,2020-07-21,2021-02-19,2021-06-30,2.0,0.0
2,2.0,BR,59.0,1.0,2021-01-04,2021-01-16,2021-05-28,2021-06-03,0.0,0.0
3,3.0,FM,42.0,0.0,2020-09-29,2020-11-19,2020-12-05,2021-11-18,0.0,0.0
4,4.0,GE,79.0,1.0,2020-11-26,2020-11-28,2021-11-19,2021-11-26,2.0,0.0

In [12]:
#transactions_info creation
df_transactions = pd.DataFrame()
for index in range(3000):
    df_transactions.at[index,'user_id'] = np.random.randint(0,300)
    df_transactions.at[index,'transaction_id'] = index
    df_transactions.at[index,'timestamp'] = fake.date_between(start_date=df_users.at[int(df_transactions.at[index,'user_id']),'onboarding_completed_at'],end_date='today')
    df_transactions.at[index,'event_kind'] = np.random.choice(event_kinds)
    df_transactions.at[index,'currency'] = np.random.choice(currencies)
    df_transactions.at[index,'amount_in_eur'] = round(random.uniform(0, 100000), 2)
df_transactions.head(5)

,user_id,transaction_id,timestamp,event_kind,currency,amount_in_eur
0,283.0,0.0,2020-06-20,fiat_withdrawal,EUR_ETH,92015.01
1,146.0,1.0,2018-05-24,exchange,BTC_EUR,45806.04
2,131.0,2.0,2020-01-03,crypto_deposit,EUR_BTC,23721.44
3,61.0,3.0,2020-02-14,fiat_deposit,BTC_EUR,46569.57
4,267.0,4.0,2021-05-25,exchange,ETH_EUR,31379.17

In [185]:
#Export to csv
#export_csv = df_users.to_csv (r'user_info.csv', header=True)
export_csv = df_transactions.to_csv (r'transaction_info.csv', header=True)
#Don't forget to add '.csv' at the end of the path